# Generated by Django 5.0.6 on 2024-08-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0002_usermember_delete_itmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, null=True)),
                ('guidelines', models.FileField(upload_to='uploads/')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('workprogress', models.ImageField(null=True, upload_to='image/')),
                ('crossed_date', models.DateField(null=True)),
                ('TL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
