# Generated by Django 5.0.6 on 2024-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guidelines',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
