# Generated by Django 5.0.6 on 2024-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0004_alter_project_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
