# Generated by Django 5.0.6 on 2024-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0007_alter_project_guidelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
