# Generated by Django 5.0.6 on 2024-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0010_customuser_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assign',
            field=models.IntegerField(default=1, max_length=50),
        ),
    ]
