# Generated by Django 5.0.6 on 2024-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0012_remove_customuser_assign_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assign',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='Assign',
        ),
    ]
