# Generated by Django 5.0.6 on 2024-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0013_customuser_assign_delete_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
