# Generated by Django 5.0.6 on 2024-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0015_assigntl'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntl',
            name='assign',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
