# Generated by Django 5.0.6 on 2024-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0017_remove_customuser_assign_usermember_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='assign',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
