# Generated by Django 5.0.6 on 2024-08-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0019_alter_usermember_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='TL',
            new_name='c_user',
        ),
        migrations.AddField(
            model_name='project',
            name='u_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.usermember'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='assign',
            field=models.CharField(max_length=50),
        ),
    ]
