# Generated by Django 5.0.6 on 2024-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0022_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='crossed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='workprogress',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
