# Generated by Django 5.0.6 on 2024-08-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0023_module_crossed_date_module_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='crossed_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
