# Generated by Django 5.0.6 on 2024-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0024_alter_module_crossed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='crossed_date',
            field=models.DateField(null=True),
        ),
    ]
