# Generated by Django 5.0.6 on 2024-08-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0025_alter_module_crossed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='crossed_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
