# Generated by Django 5.0.6 on 2024-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0027_alter_project_crossed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='connect_dev',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
