# Generated by Django 5.0.6 on 2024-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0028_module_connect_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workprogress',
            field=models.ImageField(default="static/images/'start.webp", upload_to='image/'),
        ),
    ]
