# Generated by Django 5.0.6 on 2024-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0031_alter_project_workprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workprogress',
            field=models.ImageField(default='images/it.jpg', upload_to='image/'),
        ),
    ]
