# Generated by Django 5.0.6 on 2024-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0032_alter_project_workprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workprogress',
            field=models.ImageField(default='images/start2.webp', upload_to='image/'),
        ),
    ]
