# Generated by Django 5.0.6 on 2024-08-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0035_customuser_epwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='workprogress',
            field=models.ImageField(default='images/not started.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workprogress',
            field=models.ImageField(default='images/not started.jpg', upload_to='image/'),
        ),
    ]
