# Generated by Django 5.0.6 on 2024-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0036_alter_module_workprogress_alter_project_workprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='workprogress',
            field=models.ImageField(default='images/notstarted.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workprogress',
            field=models.ImageField(default='images/notstarted.jpg', upload_to='image/'),
        ),
    ]
