# Generated by Django 5.0.6 on 2024-08-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0042_project_cl_address_project_cl_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cl_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
