# Generated by Django 5.0.6 on 2024-08-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0043_alter_project_cl_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_TL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.project')),
                ('team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.usermember')),
            ],
        ),
    ]
