# Generated by Django 5.0.6 on 2024-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0044_project_tl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='TL',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
