# Generated by Django 5.0.6 on 2024-09-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0046_rename_crossed_date_module_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='TL',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='connect_dev',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='crossed_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
