# Generated by Django 5.0.6 on 2024-09-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0047_module_tl_module_connect_dev_module_crossed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='TL',
        ),
        migrations.RemoveField(
            model_name='module',
            name='connect_dev',
        ),
        migrations.RemoveField(
            model_name='module',
            name='u_member',
        ),
    ]
