# Generated by Django 5.0.6 on 2024-09-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0049_alter_module_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='module_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.usermember')),
                ('modu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.module')),
            ],
        ),
    ]
