# Generated by Django 5.0.6 on 2024-09-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0051_teamlead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamlead',
            old_name='dev',
            new_name='tl',
        ),
    ]
