# Generated by Django 5.0.6 on 2024-09-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0053_alter_teamlead_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.teamlead'),
        ),
    ]
