# Generated by Django 5.0.6 on 2024-09-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0054_usermember_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('p_tl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.project_tl')),
            ],
        ),
    ]
