# Generated by Django 5.0.6 on 2024-09-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0055_p_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('m_dev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.module_dev')),
            ],
        ),
    ]
