# Generated by Django 5.0.6 on 2024-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0056_m_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_tl',
            name='newcount',
            field=models.IntegerField(null=True),
        ),
    ]
