# Generated by Django 5.0.6 on 2024-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0057_project_tl_newcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_dev',
            name='mod_count',
            field=models.IntegerField(null=True),
        ),
    ]
