# Generated by Django 5.0.6 on 2024-09-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0058_module_dev_mod_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_App.usermember'),
        ),
    ]
