# Generated by Django 5.0.6 on 2024-09-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0059_module_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
