# Generated by Django 5.0.6 on 2024-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_App', '0062_remove_project_crossed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crossed_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
